### ISSUE TITLE
DECISIONS_COUNT evaluates to non integer in python3

### ISSUE THREAD

**Issue by green4free** [agrimagsrl/micromlgen#1]
The following line
`n_classes * (n_classes - 1) / 2`
returns a float instead of an int on my machine, this is a problem when it is used as an array size later in the C code.

division seems to always return a float in python3, so it should probably  be changed to integer division as this works for both python 2 and 3:
`n_classes * (n_classes - 1) // 2`

**Comment by agrimagsrl** [comment]
Thank you for pointing out, I fixed this.
Also please note I'm going to delete this repo, since development has moved to https://github.com/eloquentarduino/micromlgen. That's the repo for the PyPi package.
